# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CollectorPane.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QPushButton, QRadioButton, QSizePolicy, QTextEdit,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(478, 309)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(0, 0))
        self.CollectorGroup = QGroupBox(Form)
        self.CollectorGroup.setObjectName(u"CollectorGroup")
        self.CollectorGroup.setGeometry(QRect(0, 0, 471, 301))
        sizePolicy.setHeightForWidth(self.CollectorGroup.sizePolicy().hasHeightForWidth())
        self.CollectorGroup.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.CollectorGroup.setFont(font)
        self.OffPushButton = QPushButton(self.CollectorGroup)
        self.OffPushButton.setObjectName(u"OffPushButton")
        self.OffPushButton.setGeometry(QRect(10, 270, 41, 24))
        sizePolicy.setHeightForWidth(self.OffPushButton.sizePolicy().hasHeightForWidth())
        self.OffPushButton.setSizePolicy(sizePolicy)
        self.HomePushButton = QPushButton(self.CollectorGroup)
        self.HomePushButton.setObjectName(u"HomePushButton")
        self.HomePushButton.setGeometry(QRect(60, 270, 41, 24))
        sizePolicy.setHeightForWidth(self.HomePushButton.sizePolicy().hasHeightForWidth())
        self.HomePushButton.setSizePolicy(sizePolicy)
        self.TrackPushButton = QPushButton(self.CollectorGroup)
        self.TrackPushButton.setObjectName(u"TrackPushButton")
        self.TrackPushButton.setGeometry(QRect(110, 270, 41, 24))
        sizePolicy.setHeightForWidth(self.TrackPushButton.sizePolicy().hasHeightForWidth())
        self.TrackPushButton.setSizePolicy(sizePolicy)
        self.StowPushButton = QPushButton(self.CollectorGroup)
        self.StowPushButton.setObjectName(u"StowPushButton")
        self.StowPushButton.setGeometry(QRect(160, 270, 41, 24))
        sizePolicy.setHeightForWidth(self.StowPushButton.sizePolicy().hasHeightForWidth())
        self.StowPushButton.setSizePolicy(sizePolicy)
        self.SetTimePushButton = QPushButton(self.CollectorGroup)
        self.SetTimePushButton.setObjectName(u"SetTimePushButton")
        self.SetTimePushButton.setGeometry(QRect(208, 270, 61, 24))
        sizePolicy.setHeightForWidth(self.SetTimePushButton.sizePolicy().hasHeightForWidth())
        self.SetTimePushButton.setSizePolicy(sizePolicy)
        self.RebootPushButton = QPushButton(self.CollectorGroup)
        self.RebootPushButton.setObjectName(u"RebootPushButton")
        self.RebootPushButton.setGeometry(QRect(410, 270, 51, 24))
        sizePolicy.setHeightForWidth(self.RebootPushButton.sizePolicy().hasHeightForWidth())
        self.RebootPushButton.setSizePolicy(sizePolicy)
        self.AzGroup = QGroupBox(self.CollectorGroup)
        self.AzGroup.setObjectName(u"AzGroup")
        self.AzGroup.setGeometry(QRect(10, 40, 141, 57))
        sizePolicy.setHeightForWidth(self.AzGroup.sizePolicy().hasHeightForWidth())
        self.AzGroup.setSizePolicy(sizePolicy)
        self.AzLimLowButton = QRadioButton(self.AzGroup)
        self.AzLimLowButton.setObjectName(u"AzLimLowButton")
        self.AzLimLowButton.setGeometry(QRect(80, 38, 51, 16))
        sizePolicy.setHeightForWidth(self.AzLimLowButton.sizePolicy().hasHeightForWidth())
        self.AzLimLowButton.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.AzLimLowButton.setFont(font1)
        self.AzLimLowButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.AzLimLowButton.setAutoExclusive(False)
        self.AzLimHighButton = QRadioButton(self.AzGroup)
        self.AzLimHighButton.setObjectName(u"AzLimHighButton")
        self.AzLimHighButton.setGeometry(QRect(80, 18, 51, 22))
        sizePolicy.setHeightForWidth(self.AzLimHighButton.sizePolicy().hasHeightForWidth())
        self.AzLimHighButton.setSizePolicy(sizePolicy)
        self.AzLimHighButton.setFont(font1)
        self.AzLimHighButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.AzLimHighButton.setCheckable(True)
        self.AzLimHighButton.setAutoExclusive(False)
        self.AzPosLabel = QLabel(self.AzGroup)
        self.AzPosLabel.setObjectName(u"AzPosLabel")
        self.AzPosLabel.setGeometry(QRect(10, 20, 71, 16))
        sizePolicy.setHeightForWidth(self.AzPosLabel.sizePolicy().hasHeightForWidth())
        self.AzPosLabel.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        self.AzPosLabel.setFont(font2)
        self.AzVelLabel = QLabel(self.AzGroup)
        self.AzVelLabel.setObjectName(u"AzVelLabel")
        self.AzVelLabel.setGeometry(QRect(10, 38, 71, 16))
        sizePolicy.setHeightForWidth(self.AzVelLabel.sizePolicy().hasHeightForWidth())
        self.AzVelLabel.setSizePolicy(sizePolicy)
        self.AzVelLabel.setFont(font2)
        self.ElGroup = QGroupBox(self.CollectorGroup)
        self.ElGroup.setObjectName(u"ElGroup")
        self.ElGroup.setGeometry(QRect(10, 100, 141, 57))
        sizePolicy.setHeightForWidth(self.ElGroup.sizePolicy().hasHeightForWidth())
        self.ElGroup.setSizePolicy(sizePolicy)
        self.ElLimLowButton = QRadioButton(self.ElGroup)
        self.ElLimLowButton.setObjectName(u"ElLimLowButton")
        self.ElLimLowButton.setGeometry(QRect(80, 36, 51, 22))
        sizePolicy.setHeightForWidth(self.ElLimLowButton.sizePolicy().hasHeightForWidth())
        self.ElLimLowButton.setSizePolicy(sizePolicy)
        self.ElLimLowButton.setFont(font1)
        self.ElLimLowButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.ElLimLowButton.setAutoExclusive(False)
        self.ElLimHighButton = QRadioButton(self.ElGroup)
        self.ElLimHighButton.setObjectName(u"ElLimHighButton")
        self.ElLimHighButton.setGeometry(QRect(80, 18, 51, 22))
        sizePolicy.setHeightForWidth(self.ElLimHighButton.sizePolicy().hasHeightForWidth())
        self.ElLimHighButton.setSizePolicy(sizePolicy)
        self.ElLimHighButton.setFont(font1)
        self.ElLimHighButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.ElLimHighButton.setCheckable(True)
        self.ElLimHighButton.setAutoExclusive(False)
        self.ElPosLabel = QLabel(self.ElGroup)
        self.ElPosLabel.setObjectName(u"ElPosLabel")
        self.ElPosLabel.setGeometry(QRect(10, 20, 71, 16))
        sizePolicy.setHeightForWidth(self.ElPosLabel.sizePolicy().hasHeightForWidth())
        self.ElPosLabel.setSizePolicy(sizePolicy)
        self.ElPosLabel.setFont(font2)
        self.ElVelLabel = QLabel(self.ElGroup)
        self.ElVelLabel.setObjectName(u"ElVelLabel")
        self.ElVelLabel.setGeometry(QRect(10, 38, 71, 16))
        sizePolicy.setHeightForWidth(self.ElVelLabel.sizePolicy().hasHeightForWidth())
        self.ElVelLabel.setSizePolicy(sizePolicy)
        self.ElVelLabel.setFont(font2)
        self.groupBox_5 = QGroupBox(self.CollectorGroup)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(155, 40, 81, 91))
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.WideUp = QLabel(self.groupBox_5)
        self.WideUp.setObjectName(u"WideUp")
        self.WideUp.setGeometry(QRect(23, 20, 41, 16))
        sizePolicy.setHeightForWidth(self.WideUp.sizePolicy().hasHeightForWidth())
        self.WideUp.setSizePolicy(sizePolicy)
        self.WideUp.setFont(font2)
        self.WideDown = QLabel(self.groupBox_5)
        self.WideDown.setObjectName(u"WideDown")
        self.WideDown.setGeometry(QRect(23, 49, 41, 16))
        sizePolicy.setHeightForWidth(self.WideDown.sizePolicy().hasHeightForWidth())
        self.WideDown.setSizePolicy(sizePolicy)
        self.WideDown.setFont(font2)
        self.WideLeft = QLabel(self.groupBox_5)
        self.WideLeft.setObjectName(u"WideLeft")
        self.WideLeft.setGeometry(QRect(4, 35, 41, 16))
        sizePolicy.setHeightForWidth(self.WideLeft.sizePolicy().hasHeightForWidth())
        self.WideLeft.setSizePolicy(sizePolicy)
        self.WideLeft.setFont(font2)
        self.WideRight = QLabel(self.groupBox_5)
        self.WideRight.setObjectName(u"WideRight")
        self.WideRight.setGeometry(QRect(43, 35, 41, 16))
        sizePolicy.setHeightForWidth(self.WideRight.sizePolicy().hasHeightForWidth())
        self.WideRight.setSizePolicy(sizePolicy)
        self.WideRight.setFont(font2)
        self.WideIntensity = QLabel(self.groupBox_5)
        self.WideIntensity.setObjectName(u"WideIntensity")
        self.WideIntensity.setGeometry(QRect(0, 60, 81, 30))
        sizePolicy.setHeightForWidth(self.WideIntensity.sizePolicy().hasHeightForWidth())
        self.WideIntensity.setSizePolicy(sizePolicy)
        self.WideIntensity.setFont(font2)
        self.groupBox_6 = QGroupBox(self.CollectorGroup)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(240, 40, 81, 91))
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.NarrowUp = QLabel(self.groupBox_6)
        self.NarrowUp.setObjectName(u"NarrowUp")
        self.NarrowUp.setGeometry(QRect(23, 20, 41, 16))
        sizePolicy.setHeightForWidth(self.NarrowUp.sizePolicy().hasHeightForWidth())
        self.NarrowUp.setSizePolicy(sizePolicy)
        self.NarrowUp.setFont(font2)
        self.NarrowDown = QLabel(self.groupBox_6)
        self.NarrowDown.setObjectName(u"NarrowDown")
        self.NarrowDown.setGeometry(QRect(23, 49, 41, 16))
        sizePolicy.setHeightForWidth(self.NarrowDown.sizePolicy().hasHeightForWidth())
        self.NarrowDown.setSizePolicy(sizePolicy)
        self.NarrowDown.setFont(font2)
        self.NarrowLeft = QLabel(self.groupBox_6)
        self.NarrowLeft.setObjectName(u"NarrowLeft")
        self.NarrowLeft.setGeometry(QRect(4, 35, 41, 16))
        sizePolicy.setHeightForWidth(self.NarrowLeft.sizePolicy().hasHeightForWidth())
        self.NarrowLeft.setSizePolicy(sizePolicy)
        self.NarrowLeft.setFont(font2)
        self.NarrowRight = QLabel(self.groupBox_6)
        self.NarrowRight.setObjectName(u"NarrowRight")
        self.NarrowRight.setGeometry(QRect(43, 35, 41, 16))
        sizePolicy.setHeightForWidth(self.NarrowRight.sizePolicy().hasHeightForWidth())
        self.NarrowRight.setSizePolicy(sizePolicy)
        self.NarrowRight.setFont(font2)
        self.WideIntensity_2 = QLabel(self.groupBox_6)
        self.WideIntensity_2.setObjectName(u"WideIntensity_2")
        self.WideIntensity_2.setGeometry(QRect(0, 60, 81, 30))
        sizePolicy.setHeightForWidth(self.WideIntensity_2.sizePolicy().hasHeightForWidth())
        self.WideIntensity_2.setSizePolicy(sizePolicy)
        self.WideIntensity_2.setFont(font2)
        self.State = QLabel(self.CollectorGroup)
        self.State.setObjectName(u"State")
        self.State.setGeometry(QRect(10, 20, 221, 20))
        sizePolicy.setHeightForWidth(self.State.sizePolicy().hasHeightForWidth())
        self.State.setSizePolicy(sizePolicy)
        self.State.setFont(font)
        self.groupBox_7 = QGroupBox(self.CollectorGroup)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(320, 20, 141, 137))
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label = QLabel(self.groupBox_7)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(3, 25, 90, 16))
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFont(font2)
        self.label_2 = QLabel(self.groupBox_7)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(3, 52, 101, 16))
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFont(font2)
        self.label_3 = QLabel(self.groupBox_7)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(3, 97, 90, 16))
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFont(font2)
        self.ImpliedSkyBGLabel = QLabel(self.groupBox_7)
        self.ImpliedSkyBGLabel.setObjectName(u"ImpliedSkyBGLabel")
        self.ImpliedSkyBGLabel.setGeometry(QRect(3, 75, 141, 16))
        sizePolicy.setHeightForWidth(self.ImpliedSkyBGLabel.sizePolicy().hasHeightForWidth())
        self.ImpliedSkyBGLabel.setSizePolicy(sizePolicy)
        self.ImpliedSkyBGLabel.setFont(font2)
        self.label_5 = QLabel(self.groupBox_7)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(3, 118, 141, 16))
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFont(font2)
        self.WideIllumPercentLineEdit = QLineEdit(self.groupBox_7)
        self.WideIllumPercentLineEdit.setObjectName(u"WideIllumPercentLineEdit")
        self.WideIllumPercentLineEdit.setGeometry(QRect(102, 24, 31, 20))
        self.WideIllumPercentLineEdit.setFont(font2)
        self.WideIllumPercentLineEdit.setMaxLength(2)
        self.NarrowSkyBackgroundLineEdit = QLineEdit(self.groupBox_7)
        self.NarrowSkyBackgroundLineEdit.setObjectName(u"NarrowSkyBackgroundLineEdit")
        self.NarrowSkyBackgroundLineEdit.setGeometry(QRect(102, 50, 31, 20))
        self.NarrowSkyBackgroundLineEdit.setFont(font2)
        self.NarrowSkyBackgroundLineEdit.setMaxLength(2)
        self.NarrowIllumPercentLineEdit = QLineEdit(self.groupBox_7)
        self.NarrowIllumPercentLineEdit.setObjectName(u"NarrowIllumPercentLineEdit")
        self.NarrowIllumPercentLineEdit.setGeometry(QRect(102, 95, 31, 20))
        self.NarrowIllumPercentLineEdit.setFont(font2)
        self.NarrowIllumPercentLineEdit.setMaxLength(2)
        self.CollectorLog = QTextEdit(self.CollectorGroup)
        self.CollectorLog.setObjectName(u"CollectorLog")
        self.CollectorLog.setGeometry(QRect(10, 160, 451, 107))
        sizePolicy.setHeightForWidth(self.CollectorLog.sizePolicy().hasHeightForWidth())
        self.CollectorLog.setSizePolicy(sizePolicy)
        self.CollectorLog.setFont(font1)
        self.CollectorLog.setReadOnly(True)
        self.XPos = QLabel(self.CollectorGroup)
        self.XPos.setObjectName(u"XPos")
        self.XPos.setGeometry(QRect(175, 134, 51, 20))
        sizePolicy.setHeightForWidth(self.XPos.sizePolicy().hasHeightForWidth())
        self.XPos.setSizePolicy(sizePolicy)
        self.XPos.setFont(font2)
        self.YPos = QLabel(self.CollectorGroup)
        self.YPos.setObjectName(u"YPos")
        self.YPos.setGeometry(QRect(242, 134, 51, 20))
        sizePolicy.setHeightForWidth(self.YPos.sizePolicy().hasHeightForWidth())
        self.YPos.setSizePolicy(sizePolicy)
        self.YPos.setFont(font2)
        self.MotorStatusPushButton = QPushButton(self.CollectorGroup)
        self.MotorStatusPushButton.setObjectName(u"MotorStatusPushButton")
        self.MotorStatusPushButton.setGeometry(QRect(276, 270, 71, 24))
        sizePolicy.setHeightForWidth(self.MotorStatusPushButton.sizePolicy().hasHeightForWidth())
        self.MotorStatusPushButton.setSizePolicy(sizePolicy)
        self.TimeLabel = QLabel(self.CollectorGroup)
        self.TimeLabel.setObjectName(u"TimeLabel")
        self.TimeLabel.setGeometry(QRect(250, 20, 70, 20))
        sizePolicy.setHeightForWidth(self.TimeLabel.sizePolicy().hasHeightForWidth())
        self.TimeLabel.setSizePolicy(sizePolicy)
        self.TimeLabel.setFont(font2)
        self.RebootPushButton_2 = QPushButton(self.CollectorGroup)
        self.RebootPushButton_2.setObjectName(u"RebootPushButton_2")
        self.RebootPushButton_2.setGeometry(QRect(353, 270, 51, 24))
        sizePolicy.setHeightForWidth(self.RebootPushButton_2.sizePolicy().hasHeightForWidth())
        self.RebootPushButton_2.setSizePolicy(sizePolicy)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.CollectorGroup.setTitle(QCoreApplication.translate("Form", u"Collector 0A", None))
        self.OffPushButton.setText(QCoreApplication.translate("Form", u"Off", None))
        self.HomePushButton.setText(QCoreApplication.translate("Form", u"Home", None))
        self.TrackPushButton.setText(QCoreApplication.translate("Form", u"Track", None))
        self.StowPushButton.setText(QCoreApplication.translate("Form", u"Stow", None))
        self.SetTimePushButton.setText(QCoreApplication.translate("Form", u"SetTime", None))
        self.RebootPushButton.setText(QCoreApplication.translate("Form", u"Reboot", None))
        self.AzGroup.setTitle(QCoreApplication.translate("Form", u"Az - PosMode", None))
        self.AzLimLowButton.setText(QCoreApplication.translate("Form", u"Low", None))
        self.AzLimHighButton.setText(QCoreApplication.translate("Form", u"High", None))
        self.AzPosLabel.setText(QCoreApplication.translate("Form", u"P: 000000", None))
        self.AzVelLabel.setText(QCoreApplication.translate("Form", u"V:  00000", None))
        self.ElGroup.setTitle(QCoreApplication.translate("Form", u"El - PosMode", None))
        self.ElLimLowButton.setText(QCoreApplication.translate("Form", u"Low", None))
        self.ElLimHighButton.setText(QCoreApplication.translate("Form", u"High", None))
        self.ElPosLabel.setText(QCoreApplication.translate("Form", u"P: 000000", None))
        self.ElVelLabel.setText(QCoreApplication.translate("Form", u"V:  00000", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Form", u"Wide", None))
        self.WideUp.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideDown.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideLeft.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideRight.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideIntensity.setText(QCoreApplication.translate("Form", u"  00% 00000", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Form", u"Narrow", None))
        self.NarrowUp.setText(QCoreApplication.translate("Form", u"00000", None))
        self.NarrowDown.setText(QCoreApplication.translate("Form", u"00000", None))
        self.NarrowLeft.setText(QCoreApplication.translate("Form", u"00000", None))
        self.NarrowRight.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideIntensity_2.setText(QCoreApplication.translate("Form", u"  00% 00000", None))
        self.State.setText(QCoreApplication.translate("Form", u"CurrentState", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Form", u"Thresholds", None))
        self.label.setText(QCoreApplication.translate("Form", u"WideIllum %", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"NarrowSkyBG %", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"NarrowIllum %", None))
        self.ImpliedSkyBGLabel.setText(QCoreApplication.translate("Form", u"Implied Sky BG:", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"NarrowThresh:", None))
        self.WideIllumPercentLineEdit.setText(QCoreApplication.translate("Form", u" 0", None))
        self.NarrowSkyBackgroundLineEdit.setText(QCoreApplication.translate("Form", u" 0", None))
        self.NarrowIllumPercentLineEdit.setText(QCoreApplication.translate("Form", u" 0", None))
        self.XPos.setText(QCoreApplication.translate("Form", u"X: +0.00", None))
        self.YPos.setText(QCoreApplication.translate("Form", u"Y: +0.00", None))
        self.MotorStatusPushButton.setText(QCoreApplication.translate("Form", u"MotStatus", None))
        self.TimeLabel.setText(QCoreApplication.translate("Form", u"HH:MM:SS", None))
        self.RebootPushButton_2.setText(QCoreApplication.translate("Form", u"Unstick", None))
    # retranslateUi

