# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CollectorPane.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QPushButton, QRadioButton, QSizePolicy, QTextEdit,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(478, 309)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(0, 0))
        self.CollectorGroup = QGroupBox(Form)
        self.CollectorGroup.setObjectName(u"CollectorGroup")
        self.CollectorGroup.setGeometry(QRect(0, 0, 471, 301))
        sizePolicy.setHeightForWidth(self.CollectorGroup.sizePolicy().hasHeightForWidth())
        self.CollectorGroup.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.CollectorGroup.setFont(font)
        self.OffPushButton = QPushButton(self.CollectorGroup)
        self.OffPushButton.setObjectName(u"OffPushButton")
        self.OffPushButton.setGeometry(QRect(10, 270, 41, 24))
        sizePolicy.setHeightForWidth(self.OffPushButton.sizePolicy().hasHeightForWidth())
        self.OffPushButton.setSizePolicy(sizePolicy)
        self.HomePushButton = QPushButton(self.CollectorGroup)
        self.HomePushButton.setObjectName(u"HomePushButton")
        self.HomePushButton.setGeometry(QRect(60, 270, 41, 24))
        sizePolicy.setHeightForWidth(self.HomePushButton.sizePolicy().hasHeightForWidth())
        self.HomePushButton.setSizePolicy(sizePolicy)
        self.TrackPushButton = QPushButton(self.CollectorGroup)
        self.TrackPushButton.setObjectName(u"TrackPushButton")
        self.TrackPushButton.setGeometry(QRect(110, 270, 41, 24))
        sizePolicy.setHeightForWidth(self.TrackPushButton.sizePolicy().hasHeightForWidth())
        self.TrackPushButton.setSizePolicy(sizePolicy)
        self.StowPushButton = QPushButton(self.CollectorGroup)
        self.StowPushButton.setObjectName(u"StowPushButton")
        self.StowPushButton.setGeometry(QRect(160, 270, 41, 24))
        sizePolicy.setHeightForWidth(self.StowPushButton.sizePolicy().hasHeightForWidth())
        self.StowPushButton.setSizePolicy(sizePolicy)
        self.SetTimePushButton = QPushButton(self.CollectorGroup)
        self.SetTimePushButton.setObjectName(u"SetTimePushButton")
        self.SetTimePushButton.setGeometry(QRect(208, 270, 61, 24))
        sizePolicy.setHeightForWidth(self.SetTimePushButton.sizePolicy().hasHeightForWidth())
        self.SetTimePushButton.setSizePolicy(sizePolicy)
        self.RebootPushButton = QPushButton(self.CollectorGroup)
        self.RebootPushButton.setObjectName(u"RebootPushButton")
        self.RebootPushButton.setGeometry(QRect(410, 270, 51, 24))
        sizePolicy.setHeightForWidth(self.RebootPushButton.sizePolicy().hasHeightForWidth())
        self.RebootPushButton.setSizePolicy(sizePolicy)
        self.AzGroup = QGroupBox(self.CollectorGroup)
        self.AzGroup.setObjectName(u"AzGroup")
        self.AzGroup.setGeometry(QRect(10, 40, 141, 57))
        sizePolicy.setHeightForWidth(self.AzGroup.sizePolicy().hasHeightForWidth())
        self.AzGroup.setSizePolicy(sizePolicy)
        self.AzLimLowButton = QRadioButton(self.AzGroup)
        self.AzLimLowButton.setObjectName(u"AzLimLowButton")
        self.AzLimLowButton.setGeometry(QRect(80, 38, 51, 16))
        sizePolicy.setHeightForWidth(self.AzLimLowButton.sizePolicy().hasHeightForWidth())
        self.AzLimLowButton.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.AzLimLowButton.setFont(font1)
        self.AzLimLowButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.AzLimLowButton.setAutoExclusive(False)
        self.AzLimHighButton = QRadioButton(self.AzGroup)
        self.AzLimHighButton.setObjectName(u"AzLimHighButton")
        self.AzLimHighButton.setGeometry(QRect(80, 18, 51, 22))
        sizePolicy.setHeightForWidth(self.AzLimHighButton.sizePolicy().hasHeightForWidth())
        self.AzLimHighButton.setSizePolicy(sizePolicy)
        self.AzLimHighButton.setFont(font1)
        self.AzLimHighButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.AzLimHighButton.setCheckable(True)
        self.AzLimHighButton.setAutoExclusive(False)
        self.AzPosLabel = QLabel(self.AzGroup)
        self.AzPosLabel.setObjectName(u"AzPosLabel")
        self.AzPosLabel.setGeometry(QRect(10, 20, 71, 16))
        sizePolicy.setHeightForWidth(self.AzPosLabel.sizePolicy().hasHeightForWidth())
        self.AzPosLabel.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        self.AzPosLabel.setFont(font2)
        self.AzVelLabel = QLabel(self.AzGroup)
        self.AzVelLabel.setObjectName(u"AzVelLabel")
        self.AzVelLabel.setGeometry(QRect(10, 38, 71, 16))
        sizePolicy.setHeightForWidth(self.AzVelLabel.sizePolicy().hasHeightForWidth())
        self.AzVelLabel.setSizePolicy(sizePolicy)
        self.AzVelLabel.setFont(font2)
        self.ElGroup = QGroupBox(self.CollectorGroup)
        self.ElGroup.setObjectName(u"ElGroup")
        self.ElGroup.setGeometry(QRect(10, 100, 141, 57))
        sizePolicy.setHeightForWidth(self.ElGroup.sizePolicy().hasHeightForWidth())
        self.ElGroup.setSizePolicy(sizePolicy)
        self.ElLimLowButton = QRadioButton(self.ElGroup)
        self.ElLimLowButton.setObjectName(u"ElLimLowButton")
        self.ElLimLowButton.setGeometry(QRect(80, 36, 51, 22))
        sizePolicy.setHeightForWidth(self.ElLimLowButton.sizePolicy().hasHeightForWidth())
        self.ElLimLowButton.setSizePolicy(sizePolicy)
        self.ElLimLowButton.setFont(font1)
        self.ElLimLowButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.ElLimLowButton.setAutoExclusive(False)
        self.ElLimHighButton = QRadioButton(self.ElGroup)
        self.ElLimHighButton.setObjectName(u"ElLimHighButton")
        self.ElLimHighButton.setGeometry(QRect(80, 18, 51, 22))
        sizePolicy.setHeightForWidth(self.ElLimHighButton.sizePolicy().hasHeightForWidth())
        self.ElLimHighButton.setSizePolicy(sizePolicy)
        self.ElLimHighButton.setFont(font1)
        self.ElLimHighButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.ElLimHighButton.setCheckable(True)
        self.ElLimHighButton.setAutoExclusive(False)
        self.ElPosLabel = QLabel(self.ElGroup)
        self.ElPosLabel.setObjectName(u"ElPosLabel")
        self.ElPosLabel.setGeometry(QRect(10, 20, 71, 16))
        sizePolicy.setHeightForWidth(self.ElPosLabel.sizePolicy().hasHeightForWidth())
        self.ElPosLabel.setSizePolicy(sizePolicy)
        self.ElPosLabel.setFont(font2)
        self.ElVelLabel = QLabel(self.ElGroup)
        self.ElVelLabel.setObjectName(u"ElVelLabel")
        self.ElVelLabel.setGeometry(QRect(10, 38, 71, 16))
        sizePolicy.setHeightForWidth(self.ElVelLabel.sizePolicy().hasHeightForWidth())
        self.ElVelLabel.setSizePolicy(sizePolicy)
        self.ElVelLabel.setFont(font2)
        self.WideGroup = QGroupBox(self.CollectorGroup)
        self.WideGroup.setObjectName(u"WideGroup")
        self.WideGroup.setGeometry(QRect(155, 40, 81, 91))
        sizePolicy.setHeightForWidth(self.WideGroup.sizePolicy().hasHeightForWidth())
        self.WideGroup.setSizePolicy(sizePolicy)
        self.WideUL = QLabel(self.WideGroup)
        self.WideUL.setObjectName(u"WideUL")
        self.WideUL.setGeometry(QRect(4, 20, 41, 16))
        sizePolicy.setHeightForWidth(self.WideUL.sizePolicy().hasHeightForWidth())
        self.WideUL.setSizePolicy(sizePolicy)
        self.WideUL.setFont(font2)
        self.WideLR = QLabel(self.WideGroup)
        self.WideLR.setObjectName(u"WideLR")
        self.WideLR.setGeometry(QRect(43, 41, 41, 16))
        sizePolicy.setHeightForWidth(self.WideLR.sizePolicy().hasHeightForWidth())
        self.WideLR.setSizePolicy(sizePolicy)
        self.WideLR.setFont(font2)
        self.WideLL = QLabel(self.WideGroup)
        self.WideLL.setObjectName(u"WideLL")
        self.WideLL.setGeometry(QRect(4, 41, 41, 16))
        sizePolicy.setHeightForWidth(self.WideLL.sizePolicy().hasHeightForWidth())
        self.WideLL.setSizePolicy(sizePolicy)
        self.WideLL.setFont(font2)
        self.WideUR = QLabel(self.WideGroup)
        self.WideUR.setObjectName(u"WideUR")
        self.WideUR.setGeometry(QRect(43, 20, 41, 16))
        sizePolicy.setHeightForWidth(self.WideUR.sizePolicy().hasHeightForWidth())
        self.WideUR.setSizePolicy(sizePolicy)
        self.WideUR.setFont(font2)
        self.WideIntensity = QLabel(self.WideGroup)
        self.WideIntensity.setObjectName(u"WideIntensity")
        self.WideIntensity.setGeometry(QRect(0, 60, 81, 30))
        sizePolicy.setHeightForWidth(self.WideIntensity.sizePolicy().hasHeightForWidth())
        self.WideIntensity.setSizePolicy(sizePolicy)
        self.WideIntensity.setFont(font2)
        self.NarrowGroup = QGroupBox(self.CollectorGroup)
        self.NarrowGroup.setObjectName(u"NarrowGroup")
        self.NarrowGroup.setGeometry(QRect(240, 40, 81, 91))
        sizePolicy.setHeightForWidth(self.NarrowGroup.sizePolicy().hasHeightForWidth())
        self.NarrowGroup.setSizePolicy(sizePolicy)
        self.NarrowUL = QLabel(self.NarrowGroup)
        self.NarrowUL.setObjectName(u"NarrowUL")
        self.NarrowUL.setGeometry(QRect(4, 20, 41, 16))
        sizePolicy.setHeightForWidth(self.NarrowUL.sizePolicy().hasHeightForWidth())
        self.NarrowUL.setSizePolicy(sizePolicy)
        self.NarrowUL.setFont(font2)
        self.NarrowLL = QLabel(self.NarrowGroup)
        self.NarrowLL.setObjectName(u"NarrowLL")
        self.NarrowLL.setGeometry(QRect(4, 40, 41, 16))
        sizePolicy.setHeightForWidth(self.NarrowLL.sizePolicy().hasHeightForWidth())
        self.NarrowLL.setSizePolicy(sizePolicy)
        self.NarrowLL.setFont(font2)
        self.NarrowUR = QLabel(self.NarrowGroup)
        self.NarrowUR.setObjectName(u"NarrowUR")
        self.NarrowUR.setGeometry(QRect(43, 20, 41, 16))
        sizePolicy.setHeightForWidth(self.NarrowUR.sizePolicy().hasHeightForWidth())
        self.NarrowUR.setSizePolicy(sizePolicy)
        self.NarrowUR.setFont(font2)
        self.NarrowLR = QLabel(self.NarrowGroup)
        self.NarrowLR.setObjectName(u"NarrowLR")
        self.NarrowLR.setGeometry(QRect(43, 40, 41, 16))
        sizePolicy.setHeightForWidth(self.NarrowLR.sizePolicy().hasHeightForWidth())
        self.NarrowLR.setSizePolicy(sizePolicy)
        self.NarrowLR.setFont(font2)
        self.NarrowIntensity = QLabel(self.NarrowGroup)
        self.NarrowIntensity.setObjectName(u"NarrowIntensity")
        self.NarrowIntensity.setGeometry(QRect(0, 60, 81, 30))
        sizePolicy.setHeightForWidth(self.NarrowIntensity.sizePolicy().hasHeightForWidth())
        self.NarrowIntensity.setSizePolicy(sizePolicy)
        self.NarrowIntensity.setFont(font2)
        self.State = QLabel(self.CollectorGroup)
        self.State.setObjectName(u"State")
        self.State.setGeometry(QRect(10, 20, 221, 20))
        sizePolicy.setHeightForWidth(self.State.sizePolicy().hasHeightForWidth())
        self.State.setSizePolicy(sizePolicy)
        self.State.setFont(font)
        self.ThresholdGroup = QGroupBox(self.CollectorGroup)
        self.ThresholdGroup.setObjectName(u"ThresholdGroup")
        self.ThresholdGroup.setGeometry(QRect(320, 20, 141, 137))
        sizePolicy.setHeightForWidth(self.ThresholdGroup.sizePolicy().hasHeightForWidth())
        self.ThresholdGroup.setSizePolicy(sizePolicy)
        self.ThresholdGroup.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label = QLabel(self.ThresholdGroup)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(3, 25, 90, 16))
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFont(font2)
        self.label_2 = QLabel(self.ThresholdGroup)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(3, 52, 101, 16))
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFont(font2)
        self.label_3 = QLabel(self.ThresholdGroup)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(3, 97, 90, 16))
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFont(font2)
        self.ImpliedSkyBGLabel = QLabel(self.ThresholdGroup)
        self.ImpliedSkyBGLabel.setObjectName(u"ImpliedSkyBGLabel")
        self.ImpliedSkyBGLabel.setGeometry(QRect(3, 75, 141, 16))
        sizePolicy.setHeightForWidth(self.ImpliedSkyBGLabel.sizePolicy().hasHeightForWidth())
        self.ImpliedSkyBGLabel.setSizePolicy(sizePolicy)
        self.ImpliedSkyBGLabel.setFont(font2)
        self.label_5 = QLabel(self.ThresholdGroup)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(3, 118, 141, 16))
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFont(font2)
        self.WideIllumPercentLineEdit = QLineEdit(self.ThresholdGroup)
        self.WideIllumPercentLineEdit.setObjectName(u"WideIllumPercentLineEdit")
        self.WideIllumPercentLineEdit.setGeometry(QRect(102, 24, 31, 20))
        self.WideIllumPercentLineEdit.setFont(font2)
        self.WideIllumPercentLineEdit.setMaxLength(2)
        self.NarrowSkyBackgroundLineEdit = QLineEdit(self.ThresholdGroup)
        self.NarrowSkyBackgroundLineEdit.setObjectName(u"NarrowSkyBackgroundLineEdit")
        self.NarrowSkyBackgroundLineEdit.setGeometry(QRect(102, 50, 31, 20))
        self.NarrowSkyBackgroundLineEdit.setFont(font2)
        self.NarrowSkyBackgroundLineEdit.setMaxLength(2)
        self.NarrowIllumPercentLineEdit = QLineEdit(self.ThresholdGroup)
        self.NarrowIllumPercentLineEdit.setObjectName(u"NarrowIllumPercentLineEdit")
        self.NarrowIllumPercentLineEdit.setGeometry(QRect(102, 95, 31, 20))
        self.NarrowIllumPercentLineEdit.setFont(font2)
        self.NarrowIllumPercentLineEdit.setMaxLength(2)
        self.CollectorLog = QTextEdit(self.CollectorGroup)
        self.CollectorLog.setObjectName(u"CollectorLog")
        self.CollectorLog.setGeometry(QRect(10, 160, 451, 107))
        sizePolicy.setHeightForWidth(self.CollectorLog.sizePolicy().hasHeightForWidth())
        self.CollectorLog.setSizePolicy(sizePolicy)
        self.CollectorLog.setFont(font1)
        self.CollectorLog.setReadOnly(True)
        self.XPos = QLabel(self.CollectorGroup)
        self.XPos.setObjectName(u"XPos")
        self.XPos.setGeometry(QRect(175, 134, 51, 20))
        sizePolicy.setHeightForWidth(self.XPos.sizePolicy().hasHeightForWidth())
        self.XPos.setSizePolicy(sizePolicy)
        self.XPos.setFont(font2)
        self.YPos = QLabel(self.CollectorGroup)
        self.YPos.setObjectName(u"YPos")
        self.YPos.setGeometry(QRect(242, 134, 51, 20))
        sizePolicy.setHeightForWidth(self.YPos.sizePolicy().hasHeightForWidth())
        self.YPos.setSizePolicy(sizePolicy)
        self.YPos.setFont(font2)
        self.MotorStatusPushButton = QPushButton(self.CollectorGroup)
        self.MotorStatusPushButton.setObjectName(u"MotorStatusPushButton")
        self.MotorStatusPushButton.setGeometry(QRect(276, 270, 71, 24))
        sizePolicy.setHeightForWidth(self.MotorStatusPushButton.sizePolicy().hasHeightForWidth())
        self.MotorStatusPushButton.setSizePolicy(sizePolicy)
        self.TimeLabel = QLabel(self.CollectorGroup)
        self.TimeLabel.setObjectName(u"TimeLabel")
        self.TimeLabel.setGeometry(QRect(250, 20, 70, 20))
        sizePolicy.setHeightForWidth(self.TimeLabel.sizePolicy().hasHeightForWidth())
        self.TimeLabel.setSizePolicy(sizePolicy)
        self.TimeLabel.setFont(font2)
        self.UnstickPushButton = QPushButton(self.CollectorGroup)
        self.UnstickPushButton.setObjectName(u"UnstickPushButton")
        self.UnstickPushButton.setGeometry(QRect(353, 270, 51, 24))
        sizePolicy.setHeightForWidth(self.UnstickPushButton.sizePolicy().hasHeightForWidth())
        self.UnstickPushButton.setSizePolicy(sizePolicy)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.CollectorGroup.setTitle(QCoreApplication.translate("Form", u"Collector 0A", None))
        self.OffPushButton.setText(QCoreApplication.translate("Form", u"Off", None))
        self.HomePushButton.setText(QCoreApplication.translate("Form", u"Home", None))
        self.TrackPushButton.setText(QCoreApplication.translate("Form", u"Track", None))
        self.StowPushButton.setText(QCoreApplication.translate("Form", u"Stow", None))
        self.SetTimePushButton.setText(QCoreApplication.translate("Form", u"SetTime", None))
        self.RebootPushButton.setText(QCoreApplication.translate("Form", u"Reboot", None))
        self.AzGroup.setTitle(QCoreApplication.translate("Form", u"Az - PosMode", None))
        self.AzLimLowButton.setText(QCoreApplication.translate("Form", u"Low", None))
        self.AzLimHighButton.setText(QCoreApplication.translate("Form", u"High", None))
        self.AzPosLabel.setText(QCoreApplication.translate("Form", u"P: 000000", None))
        self.AzVelLabel.setText(QCoreApplication.translate("Form", u"V:  00000", None))
        self.ElGroup.setTitle(QCoreApplication.translate("Form", u"El - PosMode", None))
        self.ElLimLowButton.setText(QCoreApplication.translate("Form", u"Low", None))
        self.ElLimHighButton.setText(QCoreApplication.translate("Form", u"High", None))
        self.ElPosLabel.setText(QCoreApplication.translate("Form", u"P: 000000", None))
        self.ElVelLabel.setText(QCoreApplication.translate("Form", u"V:  00000", None))
        self.WideGroup.setTitle(QCoreApplication.translate("Form", u"Wide", None))
        self.WideUL.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideLR.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideLL.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideUR.setText(QCoreApplication.translate("Form", u"00000", None))
        self.WideIntensity.setText(QCoreApplication.translate("Form", u"  00% 00000", None))
        self.NarrowGroup.setTitle(QCoreApplication.translate("Form", u"Narrow", None))
        self.NarrowUL.setText(QCoreApplication.translate("Form", u"00000", None))
        self.NarrowLL.setText(QCoreApplication.translate("Form", u"00000", None))
        self.NarrowUR.setText(QCoreApplication.translate("Form", u"00000", None))
        self.NarrowLR.setText(QCoreApplication.translate("Form", u"00000", None))
        self.NarrowIntensity.setText(QCoreApplication.translate("Form", u"  00% 00000", None))
        self.State.setText(QCoreApplication.translate("Form", u"CurrentState", None))
        self.ThresholdGroup.setTitle(QCoreApplication.translate("Form", u"Thresholds", None))
        self.label.setText(QCoreApplication.translate("Form", u"WideIllum %", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"NarrowSkyBG %", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"NarrowIllum %", None))
        self.ImpliedSkyBGLabel.setText(QCoreApplication.translate("Form", u"Implied Sky BG:", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"NarrowThresh:", None))
        self.WideIllumPercentLineEdit.setText(QCoreApplication.translate("Form", u" 0", None))
        self.NarrowSkyBackgroundLineEdit.setText(QCoreApplication.translate("Form", u" 0", None))
        self.NarrowIllumPercentLineEdit.setText(QCoreApplication.translate("Form", u" 0", None))
        self.XPos.setText(QCoreApplication.translate("Form", u"X: +0.00", None))
        self.YPos.setText(QCoreApplication.translate("Form", u"Y: +0.00", None))
        self.MotorStatusPushButton.setText(QCoreApplication.translate("Form", u"MotStatus", None))
        self.TimeLabel.setText(QCoreApplication.translate("Form", u"HH:MM:SS", None))
        self.UnstickPushButton.setText(QCoreApplication.translate("Form", u"Unstick", None))
    # retranslateUi

