#######################################################
# NipSequencer.pyi - Type hint declarations for dynamically generated methods
#
# The transitions library defines methods dynamically at runtime, so Pylance can't know 
# about them.  Here, we declare all the methods that are defined by the transitions
# array.  The ... indicates that no implementation is being provided

from PySide6.QtCore    import QObject, Signal, QDateTime

class tNipSequencer(QObject):
  NipStateUpdate      = Signal(str)
  SunriseSunsetUpdate = Signal(QDateTime,QDateTime)
  ClearSkyGhiUpdate   = Signal(float)

  # Dynamically created methods
  def sun_is_out      (self) -> bool: ...
  def sun_is_not_out  (self) -> bool: ...
  def acquire_complete(self) -> bool: ...
  def NoDNI           (self) -> bool: ...
  def YesDNI          (self) -> bool: ...
  def Shutdown        (self) -> bool: ...
  def DoShutdown      (self) -> None: ...
  def RunStateMachine (self) -> None: ...
